;; ==== Basic moudles ====
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(require 'basic-setup)
(require 'packages)
(require 'keybind)
(require 'fringe-setup)
(require 'workspace)
(require 'comment-setup)
;; ==== Treesit ====
(add-to-list 'load-path (expand-file-name "lisp/treesit" user-emacs-directory))
(require 'treesit-setup)
(require 'treesit-modes)
;; ==== LSP ====
(add-to-list 'load-path (expand-file-name "lisp/LSP" user-emacs-directory))
(require 'lsp-setup)
(require 'lsp-servers)
;; ==== Plugins ====
(add-to-list 'load-path (expand-file-name "lisp/plugins" user-emacs-directory))
(require 'vertico-setup)
(require 'consult-setup)
(require 'vterm-setup)
(require 'corfu-setup)
(require 'vscode-dark-theme-setup)
(require 'move-dup-setup)
(require 'pdf-tools-setup)
(require 'markdown-preview-setup)
